# Generated by Django 5.0.4 on 2025-12-26 20:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('universities', '0002_alter_academicprogram_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patientprofile',
            options={},
        ),
        migrations.AlterModelOptions(
            name='studentprofile',
            options={},
        ),
        migrations.AlterModelOptions(
            name='supervisorprofile',
            options={},
        ),
        migrations.AlterModelOptions(
            name='techsupportprofile',
            options={},
        ),
        migrations.AlterModelOptions(
            name='universityadminprofile',
            options={},
        ),
        migrations.AlterField(
            model_name='patientprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='%(class)s_profile', serialize=False, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='%(class)s_profile', serialize=False, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='supervisorprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='%(class)s_profile', serialize=False, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='techsupportprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='%(class)s_profile', serialize=False, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='universityadminprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='%(class)s_profile', serialize=False, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_users', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AlterField(
            model_name='user',
            name='fcm_token',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='FCM Token'),
        ),
        migrations.AlterField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='custom_user_groups', related_query_name='custom_user', to='auth.group'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, related_name='custom_user_permissions', related_query_name='custom_user', to='auth.permission'),
        ),
        migrations.AddIndex(
            model_name='patientprofile',
            index=models.Index(fields=['created_at'], name='idx_patient_prof_created'),
        ),
        migrations.AddIndex(
            model_name='role',
            index=models.Index(fields=['name'], name='idx_roles_name'),
        ),
        migrations.AddIndex(
            model_name='studentprofile',
            index=models.Index(fields=['university'], name='idx_student_prof_univ'),
        ),
        migrations.AddIndex(
            model_name='studentprofile',
            index=models.Index(fields=['student_id'], name='idx_student_prof_sid'),
        ),
        migrations.AddIndex(
            model_name='supervisorprofile',
            index=models.Index(fields=['university'], name='idx_supervisor_prof_univ'),
        ),
        migrations.AddIndex(
            model_name='supervisorprofile',
            index=models.Index(fields=['license_number'], name='idx_supervisor_prof_lic'),
        ),
        migrations.AddIndex(
            model_name='techsupportprofile',
            index=models.Index(fields=['created_at'], name='idx_tech_support_prof_created'),
        ),
        migrations.AddIndex(
            model_name='universityadminprofile',
            index=models.Index(fields=['university'], name='idx_univ_admin_prof_univ'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email'], name='idx_users_email'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['role'], name='idx_users_role'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['is_active'], name='idx_users_active'),
        ),
    ]
