# Generated by Django 5.0.4 on 2026-01-07

import uuid
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils import timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("cases", "0004_ai_proposals_and_statuses"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Room",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Created At")),
                ("case", models.OneToOneField(help_text="Each case has exactly one messaging room", on_delete=django.db.models.deletion.CASCADE, related_name="chat_room", to="cases.case", verbose_name="Case")),
                ("participant_patient", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="patient_chat_rooms", to=settings.AUTH_USER_MODEL, verbose_name="Patient")),
                ("participant_student", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="student_chat_rooms", to=settings.AUTH_USER_MODEL, verbose_name="Student")),
            ],
            options={
                "verbose_name": "Chat Room",
                "verbose_name_plural": "Chat Rooms",
                "db_table": "messaging_rooms",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("content", models.TextField(verbose_name="Message Content")),
                ("sent_at", models.DateTimeField(default=timezone.now, verbose_name="Sent At")),
                ("is_system", models.BooleanField(default=False, help_text="True if generated automatically by the system", verbose_name="System Message")),
                ("room", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="messages", to="messaging.room", verbose_name="Room")),
                ("sender", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="sent_messages", to=settings.AUTH_USER_MODEL, verbose_name="Sender")),
            ],
            options={
                "verbose_name": "Message",
                "verbose_name_plural": "Messages",
                "db_table": "messaging_messages",
                "ordering": ["sent_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="room",
            constraint=models.CheckConstraint(
                check=~models.Q(participant_patient=models.F("participant_student")),
                name="room_participants_must_be_different",
            ),
        ),
        migrations.AddIndex(
            model_name="room",
            index=models.Index(fields=["case"], name="messaging_room_case_idx"),
        ),
        migrations.AddIndex(
            model_name="room",
            index=models.Index(fields=["participant_patient"], name="messaging_room_patient_idx"),
        ),
        migrations.AddIndex(
            model_name="room",
            index=models.Index(fields=["participant_student"], name="messaging_room_student_idx"),
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(fields=["room", "sent_at"], name="messaging_message_room_idx"),
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(fields=["sender"], name="messaging_message_sender_idx"),
        ),
    ]
