# Generated by Django 5.0.4 on 2026-01-08 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='message',
            new_name='messaging_m_room_id_1cc8af_idx',
            old_name='messaging_message_room_idx',
        ),
        migrations.RenameIndex(
            model_name='message',
            new_name='messaging_m_sender__bd59d4_idx',
            old_name='messaging_message_sender_idx',
        ),
        migrations.RenameIndex(
            model_name='room',
            new_name='messaging_r_case_id_ca8eeb_idx',
            old_name='messaging_room_case_idx',
        ),
        migrations.RenameIndex(
            model_name='room',
            new_name='messaging_r_partici_5b3dc5_idx',
            old_name='messaging_room_patient_idx',
        ),
        migrations.RenameIndex(
            model_name='room',
            new_name='messaging_r_partici_fcb665_idx',
            old_name='messaging_room_student_idx',
        ),
    ]
