# Generated by Django 5.0.4 on 2026-01-11 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0003_thread_types_and_course_rooms'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='room',
            new_name='messaging_r_course__eb68a8_idx',
            old_name='messaging_r_course_id_idx',
        ),
        migrations.RenameIndex(
            model_name='room',
            new_name='messaging_r_partici_66c892_idx',
            old_name='messaging_r_partici_sup_idx',
        ),
    ]
