# Generated by Django 5.0.4 on 2025-12-26 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='academicprogram',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='academicyear',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='faculty',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='academicprogram',
            name='code',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='academicprogram',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='academicprogram',
            name='duration_years',
            field=models.PositiveIntegerField(default=4),
        ),
        migrations.AlterField(
            model_name='academicprogram',
            name='level',
            field=models.CharField(choices=[('bachelor', 'Bachelor'), ('master', 'Master'), ('doctorate', 'Doctorate'), ('diploma', 'Diploma'), ('certificate', 'Certificate')], default='bachelor', max_length=20),
        ),
        migrations.AlterField(
            model_name='academicprogram',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='university',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='university',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='university',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='university',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='university',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='university',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='university',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='university',
            name='phone',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='university',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='university',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='academicprogram',
            index=models.Index(fields=['university', 'is_active'], name='idx_program_univ_active'),
        ),
        migrations.AddIndex(
            model_name='academicprogram',
            index=models.Index(fields=['code'], name='idx_program_code'),
        ),
        migrations.AddIndex(
            model_name='academicyear',
            index=models.Index(fields=['university', 'is_active'], name='idx_year_univ_active'),
        ),
        migrations.AddIndex(
            model_name='faculty',
            index=models.Index(fields=['university', 'is_active'], name='idx_faculty_univ_active'),
        ),
        migrations.AddIndex(
            model_name='university',
            index=models.Index(fields=['is_active'], name='idx_univ_active'),
        ),
        migrations.AddIndex(
            model_name='university',
            index=models.Index(fields=['country', 'city'], name='idx_univ_country_city'),
        ),
        migrations.AddConstraint(
            model_name='academicprogram',
            constraint=models.UniqueConstraint(fields=('university', 'code'), name='uq_program_university_code'),
        ),
        migrations.AddConstraint(
            model_name='academicyear',
            constraint=models.UniqueConstraint(fields=('university', 'name'), name='uq_academic_year_university_name'),
        ),
        migrations.AddConstraint(
            model_name='academicyear',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('university',), name='uq_one_active_academic_year_per_university'),
        ),
        migrations.AddConstraint(
            model_name='faculty',
            constraint=models.UniqueConstraint(fields=('university', 'name'), name='uq_faculty_university_name'),
        ),
    ]
