# Generated by Django 5.0.4 on 2026-01-07

import uuid
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("cases", "0004_ai_proposals_and_statuses"),
        ("appointments", "0002_rename_appointment_appoint_8b74ac_idx_idx_appt_date_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Attachment",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("file", models.FileField(upload_to="attachments/")),
                ("original_filename", models.CharField(max_length=255)),
                ("file_size", models.PositiveIntegerField()),
                ("mime_type", models.CharField(max_length=100)),
                ("file_category", models.CharField(choices=[("image", "Image"), ("document", "Document"), ("video", "Video"), ("other", "Other")], max_length=20)),
                ("attachment_type", models.CharField(choices=[("before_image", "Before Treatment Image"), ("after_image", "After Treatment Image"), ("report", "Clinical Report"), ("other", "Other")], max_length=30)),
                ("is_visible_to_patient", models.BooleanField(default=True, verbose_name="Visible to patient")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("appointment", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="attachments", to="appointments.appointment", verbose_name="Appointment")),
                ("case", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="attachments", to="cases.case", verbose_name="Case")),
                ("uploaded_by", models.ForeignKey(limit_choices_to={"role__name": "student"}, on_delete=django.db.models.deletion.PROTECT, related_name="uploaded_attachments", to=settings.AUTH_USER_MODEL, verbose_name="Uploaded By (Student)")),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="attachment",
            index=models.Index(fields=["case"], name="attachments_case_idx"),
        ),
        migrations.AddIndex(
            model_name="attachment",
            index=models.Index(fields=["appointment"], name="attachments_appointment_idx"),
        ),
        migrations.AddIndex(
            model_name="attachment",
            index=models.Index(fields=["attachment_type"], name="attachments_type_idx"),
        ),
    ]
