# Generated by Django 5.0.4 on 2026-01-08 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attachments', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='attachment',
            new_name='attachments_case_id_8369d6_idx',
            old_name='attachments_case_idx',
        ),
        migrations.RenameIndex(
            model_name='attachment',
            new_name='attachments_appoint_3b3cd0_idx',
            old_name='attachments_appointment_idx',
        ),
        migrations.RenameIndex(
            model_name='attachment',
            new_name='attachments_attachm_9b35f8_idx',
            old_name='attachments_type_idx',
        ),
    ]
