import uuid
from django.db import models
from django.utils.translation import gettext_lazy as _
from apps.accounts.models import User
from apps.universities.models import University


class Report(models.Model):
    """Report model based on ERD."""
    
    REPORT_TYPE_CHOICES = (
        ('academic', _('Academic Performance')),
        ('clinical', _('Clinical Performance')),
        ('attendance', _('Attendance')),
        ('evaluation', _('Evaluation Summary')),
        ('progress', _('Progress Report')),
        ('statistical', _('Statistical Analysis')),
        ('other', _('Other')),
    )
    
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False, verbose_name=_('ID'))
    student = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='reports',
        limit_choices_to={'role': 'student'},
        verbose_name=_('Student'),
        db_column='student_id'
    )
    report_type = models.CharField(
        max_length=50,
        choices=REPORT_TYPE_CHOICES,
        verbose_name=_('Report Type'),
        db_column='report_type'
    )
    file_url = models.TextField(
        verbose_name=_('File URL'),
        help_text=_('URL or path to the generated report file'),
        db_column='file_url'
    )
    generated_at = models.DateTimeField(
        auto_now_add=True,
        verbose_name=_('Generated At'),
        db_column='generated_at'
    )
    generated_by = models.ForeignKey(
        User,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name='generated_reports',
        verbose_name=_('Generated By'),
        help_text=_('User who generated this report'),
        db_column='generated_by'
    )
    university = models.ForeignKey(
        University,
        on_delete=models.CASCADE,
        related_name='reports',
        verbose_name=_('University'),
        db_column='university_id'
    )
    
    # Additional fields for better functionality
    title = models.CharField(
        max_length=200,
        blank=True,
        null=True,
        verbose_name=_('Title'),
        help_text=_('Optional title for the report')
    )
    description = models.TextField(
        blank=True,
        null=True,
        verbose_name=_('Description'),
        help_text=_('Optional description or notes about the report')
    )
    is_active = models.BooleanField(
        default=True,
        verbose_name=_('Is Active'),
        help_text=_('Whether this report is active and visible')
    )
    created_at = models.DateTimeField(
        auto_now_add=True,
        verbose_name=_('Created At')
    )
    updated_at = models.DateTimeField(
        auto_now=True,
        verbose_name=_('Updated At')
    )
    
    class Meta:
        db_table = 'reports'
        verbose_name = _('Report')
        verbose_name_plural = _('Reports')
        ordering = ['-generated_at']
        indexes = [
            models.Index(fields=['student', 'report_type']),
            models.Index(fields=['university', 'generated_at']),
            models.Index(fields=['generated_at']),
        ]
    
    def __str__(self):
        return f"{self.get_report_type_display()} - {self.student.username} ({self.university.name})"


