# apps/reports/models.py
import uuid
from django.db import models
from django.utils.translation import gettext_lazy as _
from django.core.exceptions import ValidationError

from apps.accounts.models import User, Role
from apps.universities.models import University


class Report(models.Model):
    """
    Governance-driven academic & clinical report.

    Workflow:
    Draft -> Submitted -> Approved -> Locked
             -> Rejected (with notes)

    Rules:
    - Immutable after approval/lock
    - Scoped by university
    """

    # ============================================================
    # Report Types
    # ============================================================
    class ReportType(models.TextChoices):
        CLINICAL_CASE = "clinical_case", _("Clinical Case Report")
        SUPERVISOR_CASE_EVALUATION = "supervisor_case_evaluation", _("Supervisor Case Evaluation")
        STUDENT_PERFORMANCE = "student_performance", _("Student Performance")
        COURSE_PERFORMANCE = "course_performance", _("Course Performance")
        UNIVERSITY_STUDENTS = "university_students", _("University Student Summary")
        UNIVERSITY_SUPERVISORS = "university_supervisors", _("University Supervisor Summary")
        UNIVERSITY_ARCHIVE = "university_archive", _("University Archive Report")
        OTHER = "other", _("Other")

    class TargetType(models.TextChoices):
        CASE = "case", _("Case")
        STUDENT = "student", _("Student")
        COURSE = "course", _("Course")
        UNIVERSITY = "university", _("University")

    class Status(models.TextChoices):
        DRAFT = "draft", _("Draft")
        SUBMITTED = "submitted", _("Submitted")
        APPROVED = "approved", _("Approved")
        REJECTED = "rejected", _("Rejected")
        LOCKED = "locked", _("Locked")

    # ============================================================
    # Core Identity
    # ============================================================
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False, verbose_name=_("ID"))

    # ============================================================
    # Academic Relations
    # ============================================================
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name="authored_reports",
        verbose_name=_("Author"),
        help_text=_("User who created the report"),
    )

    author_role = models.CharField(
        max_length=30,
        blank=True,
        verbose_name=_("Author Role"),
        help_text=_("Role snapshot at creation time"),
    )

    student = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        null=True,
        blank=True,
        related_name="academic_reports",
        # IMPORTANT: Role is FK, filter via role__name
        limit_choices_to={"role__name": Role.STUDENT},
        verbose_name=_("Student"),
        help_text=_("Student this report belongs to"),
        db_index=True,
    )

    supervisor = models.ForeignKey(
        User,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name="reviewed_reports",
        limit_choices_to={"role__name": Role.SUPERVISOR},
        verbose_name=_("Supervisor"),
        help_text=_("Supervisor linked to this report or reviewer"),
    )

    university = models.ForeignKey(
        University,
        on_delete=models.CASCADE,
        related_name="reports",
        verbose_name=_("University"),
        help_text=_("University that owns this report"),
        db_index=True,
    )

    generated_by = models.ForeignKey(
        User,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name="generated_reports",
        limit_choices_to={
            "role__name__in": [
                Role.SUPERVISOR,
                Role.UNIVERSITY_ADMIN,
            ]
        },
        verbose_name=_("Generated By"),
        help_text=_("User who generated this report"),
    )

    # ============================================================
    # Report Metadata
    # ============================================================
    report_type = models.CharField(
        max_length=50,
        choices=ReportType.choices,
        verbose_name=_("Report Type"),
        db_index=True,
    )

    target_type = models.CharField(
        max_length=20,
        choices=TargetType.choices,
        verbose_name=_("Target Type"),
        db_index=True,
    )

    target_id = models.UUIDField(
        verbose_name=_("Target ID"),
        help_text=_("Primary target identifier (case/student/course/university)."),
        db_index=True,
    )

    case_id = models.UUIDField(
        null=True,
        blank=True,
        verbose_name=_("Case ID"),
        help_text=_("Optional case identifier"),
        db_index=True,
    )

    session_id = models.UUIDField(
        null=True,
        blank=True,
        verbose_name=_("Session ID"),
        help_text=_("Optional session identifier"),
        db_index=True,
    )

    title = models.CharField(
        max_length=200,
        blank=True,
        null=True,
        verbose_name=_("Title"),
        help_text=_("Optional descriptive title for the report"),
    )

    description = models.TextField(
        blank=True,
        null=True,
        verbose_name=_("Description"),
        help_text=_("Optional notes or explanation for this report"),
    )

    content = models.JSONField(
        blank=True,
        null=True,
        verbose_name=_("Content"),
        help_text=_("Structured JSON content for the report"),
    )

    # ============================================================
    # Report Output
    # ============================================================
    file_url = models.TextField(
        blank=True,
        null=True,
        verbose_name=_("File URL"),
        help_text=_("Absolute or relative path to the generated report file (optional for media/content-based reports)"),
    )

    attachments = models.JSONField(
        blank=True,
        null=True,
        verbose_name=_("Attachments"),
        help_text=_("List of attachments with types (before/during/after/file)."),
    )

    snapshot_data = models.JSONField(
        blank=True,
        null=True,
        verbose_name=_("Snapshot Data"),
        help_text=_("Optional frozen snapshot of aggregated data (for statistics/progress)."),
    )

    score = models.PositiveSmallIntegerField(
        null=True,
        blank=True,
        verbose_name=_("Score"),
        help_text=_("Optional numeric score (0-100)."),
    )

    feedback = models.TextField(
        blank=True,
        null=True,
        verbose_name=_("Feedback / Review"),
        help_text=_("Supervisor feedback for the report."),
    )

    reviewed_at = models.DateTimeField(
        null=True,
        blank=True,
        verbose_name=_("Reviewed At"),
    )

    review_notes = models.TextField(
        blank=True,
        null=True,
        verbose_name=_("Review Notes"),
        help_text=_("Supervisor notes for approval/rejection."),
    )

    approved_by = models.ForeignKey(
        User,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name="approved_reports",
        limit_choices_to={"role__name": Role.SUPERVISOR},
        verbose_name=_("Approved By"),
    )

    approved_at = models.DateTimeField(
        null=True,
        blank=True,
        verbose_name=_("Approved At"),
    )

    submitted_at = models.DateTimeField(
        null=True,
        blank=True,
        verbose_name=_("Submitted At"),
    )

    rejected_at = models.DateTimeField(
        null=True,
        blank=True,
        verbose_name=_("Rejected At"),
    )

    locked_at = models.DateTimeField(
        null=True,
        blank=True,
        verbose_name=_("Locked At"),
    )

    status = models.CharField(
        max_length=20,
        choices=Status.choices,
        default=Status.DRAFT,
        verbose_name=_("Status"),
        db_index=True,
    )

    # ============================================================
    # Lifecycle & Visibility
    # ============================================================
    is_active = models.BooleanField(
        default=True,
        verbose_name=_("Is Active"),
        help_text=_("Soft visibility flag (reports are never deleted)"),
    )

    generated_at = models.DateTimeField(auto_now_add=True, verbose_name=_("Generated At"), db_index=True)
    created_at = models.DateTimeField(auto_now_add=True, verbose_name=_("Created At"))
    updated_at = models.DateTimeField(auto_now=True, verbose_name=_("Updated At"))

    # ============================================================
    # Meta
    # ============================================================
    class Meta:
        db_table = "reports"
        verbose_name = _("Report")
        verbose_name_plural = _("Reports")
        ordering = ["-generated_at"]
        indexes = [
            models.Index(fields=["student", "report_type"]),
            models.Index(fields=["university", "report_type"]),
            models.Index(fields=["target_type", "target_id"]),
            models.Index(fields=["generated_at"]),
            models.Index(fields=["case_id"]),
            models.Index(fields=["session_id"]),
        ]

    # ============================================================
    # Representation
    # ============================================================
    def __str__(self):
        author_name = (self.author.get_full_name() or self.author.username) if self.author_id else "Unknown"
        uni_name = self.university.name if self.university_id else "Unknown"
        return f"{self.get_report_type_display()} | {author_name} | {uni_name}"

    # ============================================================
    # Validation Guards
    # ============================================================
    def clean(self):
        if not self.author_id:
            raise ValidationError({"author": _("Author is required.")})

        if not self.target_type or not self.target_id:
            raise ValidationError({"target_id": _("Target type and id are required.")})

        # ensure student role is actually student (defensive; UI limits are not enough)
        if self.student_id and getattr(getattr(self.student, "role", None), "name", None) != Role.STUDENT:
            raise ValidationError({"student": _("Selected user must be a student.")})

        if self.approved_by_id and getattr(getattr(self.approved_by, "role", None), "name", None) != Role.SUPERVISOR:
            raise ValidationError({"approved_by": _("Approved By must be a supervisor.")})

    # ============================================================
    # Immutability (allow only is_active toggle)
    # ============================================================
    def save(self, *args, **kwargs):
        """
        Reports are immutable after approval/lock EXCEPT:
        - is_active
        - file_url (export output)
        - review_notes / approved_by / approved_at / locked_at
        """
        if not self._state.adding:
            old = Report.objects.filter(pk=self.pk).only(
                "author_id",
                "author_role",
                "student_id",
                "university_id",
                "supervisor_id",
                "generated_by_id",
                "report_type",
                "target_type",
                "target_id",
                "case_id",
                "session_id",
                "title",
                "description",
                "content",
                "file_url",
                "attachments",
                "snapshot_data",
                "score",
                "feedback",
                "reviewed_at",
                "review_notes",
                "approved_by_id",
                "approved_at",
                "submitted_at",
                "rejected_at",
                "locked_at",
                "status",
                "generated_at",
                "created_at",
                # updated_at will change automatically
                "is_active",
            ).first()

            if old is None:
                raise RuntimeError(_("Report instance not found for update."))

            if old.status in {Report.Status.APPROVED, Report.Status.LOCKED}:
                changed_forbidden = []

                def _diff(field):
                    return getattr(old, field) != getattr(self, field)

                immutable_fields = [
                    "author_id",
                    "author_role",
                    "student_id",
                    "university_id",
                    "generated_by_id",
                    "report_type",
                    "target_type",
                    "target_id",
                    "case_id",
                    "session_id",
                    "title",
                    "description",
                    "content",
                    "file_url",
                    "attachments",
                    "snapshot_data",
                    "generated_at",
                    "created_at",
                ]

                for f in immutable_fields:
                    if _diff(f):
                        changed_forbidden.append(f)

                allowed_mutable = {
                    "is_active",
                    "file_url",
                    "review_notes",
                    "approved_by_id",
                    "approved_at",
                    "locked_at",
                    "updated_at",
                }

                illegal = [f for f in changed_forbidden if f not in allowed_mutable]

                if illegal:
                    raise RuntimeError(
                        _("Reports are immutable after approval. Forbidden changes: %(fields)s")
                        % {"fields": ", ".join(illegal)}
                    )

        if not self.author_role and self.author_id:
            self.author_role = getattr(getattr(self.author, "role", None), "name", "")

        super().save(*args, **kwargs)
