import uuid
from django.db import models
from django.utils.translation import gettext_lazy as _

from apps.accounts.models import User
from apps.universities.models import University


class Report(models.Model):
    """
    Read-only analytical and academic report.

    Reports are:
    - Generated automatically or by authorized staff
    - Immutable after creation
    - Used for academic evaluation, auditing, and analytics
    """

    # ============================================================
    # Report Types
    # ============================================================

    class ReportType(models.TextChoices):
        ACADEMIC = 'academic', _('Academic Performance')
        CLINICAL = 'clinical', _('Clinical Performance')
        ATTENDANCE = 'attendance', _('Attendance')
        EVALUATION = 'evaluation', _('Evaluation Summary')
        PROGRESS = 'progress', _('Progress Report')
        STATISTICAL = 'statistical', _('Statistical Analysis')
        OTHER = 'other', _('Other')

    # ============================================================
    # Core Identity
    # ============================================================

    id = models.UUIDField(
        primary_key=True,
        default=uuid.uuid4,
        editable=False,
        verbose_name=_('ID')
    )

    # ============================================================
    # Academic Relations
    # ============================================================

    student = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='academic_reports',
        limit_choices_to={'role': 'student'},
        verbose_name=_('Student'),
        help_text=_('Student this report belongs to'),
        db_index=True
    )

    university = models.ForeignKey(
        University,
        on_delete=models.CASCADE,
        related_name='reports',
        verbose_name=_('University'),
        help_text=_('University that owns this report'),
        db_index=True
    )

    generated_by = models.ForeignKey(
        User,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name='generated_reports',
        limit_choices_to={
            'role__in': [
                'supervisor',
                'university_admin',
                'tech_support'
            ]
        },
        verbose_name=_('Generated By'),
        help_text=_('User who generated this report')
    )

    # ============================================================
    # Report Metadata
    # ============================================================

    report_type = models.CharField(
        max_length=50,
        choices=ReportType.choices,
        verbose_name=_('Report Type'),
        db_index=True
    )

    title = models.CharField(
        max_length=200,
        blank=True,
        null=True,
        verbose_name=_('Title'),
        help_text=_('Optional descriptive title for the report')
    )

    description = models.TextField(
        blank=True,
        null=True,
        verbose_name=_('Description'),
        help_text=_('Optional notes or explanation for this report')
    )

    # ============================================================
    # Report Output
    # ============================================================

    file_url = models.TextField(
        verbose_name=_('File URL'),
        help_text=_('Absolute or relative path to the generated report file')
    )

    snapshot_data = models.JSONField(
        blank=True,
        null=True,
        verbose_name=_('Snapshot Data'),
        help_text=_(
            'Optional frozen snapshot of aggregated data '
            '(used for statistical & progress reports)'
        )
    )

    # ============================================================
    # Lifecycle & Visibility
    # ============================================================

    is_active = models.BooleanField(
        default=True,
        verbose_name=_('Is Active'),
        help_text=_('Soft visibility flag (reports are never deleted)')
    )

    generated_at = models.DateTimeField(
        auto_now_add=True,
        verbose_name=_('Generated At'),
        db_index=True
    )

    created_at = models.DateTimeField(
        auto_now_add=True,
        verbose_name=_('Created At')
    )

    updated_at = models.DateTimeField(
        auto_now=True,
        verbose_name=_('Updated At')
    )

    # ============================================================
    # Meta
    # ============================================================

    class Meta:
        db_table = 'reports'
        verbose_name = _('Report')
        verbose_name_plural = _('Reports')
        ordering = ['-generated_at']
        indexes = [
            models.Index(fields=['student', 'report_type']),
            models.Index(fields=['university', 'report_type']),
            models.Index(fields=['generated_at']),
        ]

    # ============================================================
    # Representation
    # ============================================================

    def __str__(self):
        return (
            f"{self.get_report_type_display()} | "
            f"{self.student.get_full_name() or self.student.username} | "
            f"{self.university.name}"
        )

    # ============================================================
    # Safety Guards
    # ============================================================

    def save(self, *args, **kwargs):
        """
        Prevent accidental mutation of reports after creation.
        Reports are immutable once generated.
        """
        if self.pk:
            raise RuntimeError(_("Reports are immutable and cannot be modified."))
        super().save(*args, **kwargs)
