# Generated by Django 5.0.4 on 2025-12-21 20:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('universities', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('description', models.TextField(verbose_name='Description')),
                ('status', models.CharField(choices=[('new', 'New (Initial Diagnosis)'), ('pending_assignment', 'Pending Assignment'), ('assigned', 'Assigned to Student'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('closed', 'Closed (Finalized)')], default='new', max_length=30, verbose_name='Status')),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=20, verbose_name='Priority')),
                ('is_public', models.BooleanField(default=False, help_text='If true, students can request assignment.', verbose_name='Visible for Assignment')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('patient', models.ForeignKey(limit_choices_to={'role': 'patient'}, on_delete=django.db.models.deletion.CASCADE, related_name='patient_cases', to=settings.AUTH_USER_MODEL, verbose_name='Patient')),
                ('student', models.ForeignKey(blank=True, limit_choices_to={'role': 'student'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_cases', to=settings.AUTH_USER_MODEL, verbose_name='Assigned Student')),
                ('supervisor', models.ForeignKey(blank=True, limit_choices_to={'role': 'supervisor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervised_cases', to=settings.AUTH_USER_MODEL, verbose_name='Supervisor')),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cases', to='universities.university', verbose_name='University')),
            ],
            options={
                'verbose_name': 'Case',
                'verbose_name_plural': 'Cases',
                'db_table': 'cases',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CaseHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('created', 'Created'), ('assignment_requested', 'Assignment Requested'), ('assigned', 'Assigned'), ('status_changed', 'Status Changed'), ('session_created', 'Session Created'), ('session_reviewed', 'Session Reviewed'), ('completed', 'Completed'), ('closed', 'Closed')], max_length=50, verbose_name='Action')),
                ('description', models.TextField(verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='cases.case', verbose_name='Case')),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Performed By')),
            ],
            options={
                'verbose_name': 'Case History',
                'verbose_name_plural': 'Case Histories',
                'db_table': 'case_history',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CaseSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notes', models.TextField(help_text='Written by the student after the session.', verbose_name='Clinical Notes')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('completed', 'Completed by Student'), ('needs_review', 'Needs Supervisor Review'), ('approved', 'Approved by Supervisor'), ('rejected', 'Rejected by Supervisor')], default='draft', max_length=20, verbose_name='Session Status')),
                ('supervisor_feedback', models.TextField(blank=True, null=True, verbose_name='Supervisor Feedback')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='cases.case', verbose_name='Case')),
                ('student', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='case_sessions', to=settings.AUTH_USER_MODEL, verbose_name='Student')),
                ('supervisor', models.ForeignKey(blank=True, limit_choices_to={'role': 'supervisor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_sessions', to=settings.AUTH_USER_MODEL, verbose_name='Supervisor')),
            ],
            options={
                'verbose_name': 'Case Session',
                'verbose_name_plural': 'Case Sessions',
                'db_table': 'case_sessions',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='CaseAssignmentRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('message', models.TextField(blank=True, null=True, verbose_name='Student Message')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending', max_length=20, verbose_name='Status')),
                ('supervisor_response', models.TextField(blank=True, null=True, verbose_name='Supervisor Response')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_requests', to='cases.case', verbose_name='Case')),
                ('student', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='case_assignment_requests', to=settings.AUTH_USER_MODEL, verbose_name='Student')),
            ],
            options={
                'verbose_name': 'Case Assignment Request',
                'verbose_name_plural': 'Case Assignment Requests',
                'db_table': 'case_assignment_requests',
                'ordering': ['-created_at'],
                'unique_together': {('case', 'student')},
            },
        ),
    ]
