# Generated by Django 5.0.4 on 2025-12-26 20:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0001_initial'),
        ('universities', '0002_alter_academicprogram_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='caseassignmentrequest',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='case',
            name='patient',
            field=models.ForeignKey(limit_choices_to={'role__name': 'patient'}, on_delete=django.db.models.deletion.CASCADE, related_name='patient_cases', to=settings.AUTH_USER_MODEL, verbose_name='Patient'),
        ),
        migrations.AlterField(
            model_name='case',
            name='student',
            field=models.ForeignKey(blank=True, limit_choices_to={'role__name': 'student'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_cases', to=settings.AUTH_USER_MODEL, verbose_name='Assigned Student'),
        ),
        migrations.AlterField(
            model_name='case',
            name='supervisor',
            field=models.ForeignKey(blank=True, limit_choices_to={'role__name': 'supervisor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervised_cases', to=settings.AUTH_USER_MODEL, verbose_name='Supervisor'),
        ),
        migrations.AlterField(
            model_name='case',
            name='university',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cases', to='universities.university', verbose_name='University'),
        ),
        migrations.AlterField(
            model_name='caseassignmentrequest',
            name='student',
            field=models.ForeignKey(limit_choices_to={'role__name': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='case_assignment_requests', to=settings.AUTH_USER_MODEL, verbose_name='Student'),
        ),
        migrations.AlterField(
            model_name='casesession',
            name='student',
            field=models.ForeignKey(limit_choices_to={'role__name': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='case_sessions', to=settings.AUTH_USER_MODEL, verbose_name='Student'),
        ),
        migrations.AlterField(
            model_name='casesession',
            name='supervisor',
            field=models.ForeignKey(blank=True, limit_choices_to={'role__name': 'supervisor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_sessions', to=settings.AUTH_USER_MODEL, verbose_name='Supervisor'),
        ),
        migrations.AddIndex(
            model_name='case',
            index=models.Index(fields=['status'], name='idx_case_status'),
        ),
        migrations.AddIndex(
            model_name='case',
            index=models.Index(fields=['priority'], name='idx_case_priority'),
        ),
        migrations.AddIndex(
            model_name='case',
            index=models.Index(fields=['created_at'], name='idx_case_created'),
        ),
        migrations.AddIndex(
            model_name='case',
            index=models.Index(fields=['is_public'], name='idx_case_public'),
        ),
        migrations.AddIndex(
            model_name='case',
            index=models.Index(fields=['university'], name='idx_case_university'),
        ),
        migrations.AddIndex(
            model_name='case',
            index=models.Index(fields=['patient'], name='idx_case_patient'),
        ),
        migrations.AddIndex(
            model_name='case',
            index=models.Index(fields=['student'], name='idx_case_student'),
        ),
        migrations.AddIndex(
            model_name='case',
            index=models.Index(fields=['supervisor'], name='idx_case_supervisor'),
        ),
        migrations.AddIndex(
            model_name='caseassignmentrequest',
            index=models.Index(fields=['case', 'status'], name='idx_req_case_status'),
        ),
        migrations.AddIndex(
            model_name='caseassignmentrequest',
            index=models.Index(fields=['student', 'status'], name='idx_req_student_status'),
        ),
        migrations.AddIndex(
            model_name='casehistory',
            index=models.Index(fields=['case', 'created_at'], name='idx_casehistory_case_time'),
        ),
        migrations.AddIndex(
            model_name='casehistory',
            index=models.Index(fields=['action'], name='idx_casehistory_action'),
        ),
        migrations.AddIndex(
            model_name='casesession',
            index=models.Index(fields=['case', 'created_at'], name='idx_session_case_time'),
        ),
        migrations.AddIndex(
            model_name='casesession',
            index=models.Index(fields=['student', 'created_at'], name='idx_session_student_time'),
        ),
        migrations.AddIndex(
            model_name='casesession',
            index=models.Index(fields=['status'], name='idx_session_status'),
        ),
        migrations.AddConstraint(
            model_name='caseassignmentrequest',
            constraint=models.UniqueConstraint(fields=('case', 'student'), name='uq_case_student_request'),
        ),
    ]
