# Generated by Django 5.0.4 on 2026-01-04 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0002_alter_caseassignmentrequest_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='ai_metadata',
            field=models.JSONField(blank=True, help_text='Raw AI payload (severity/diagnosis/confidence).', null=True, verbose_name='AI Metadata'),
        ),
        migrations.AddField(
            model_name='case',
            name='is_ai_critical',
            field=models.BooleanField(default=False, help_text='Set when created from AI with high severity/urgency.', verbose_name='AI Critical Case'),
        ),
    ]
