# Generated by Django 5.0.4 on 2026-01-08 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0004_ai_proposals_and_statuses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='status',
            field=models.CharField(choices=[('new', 'New (Initial Diagnosis)'), ('accepted', 'Accepted by Supervisor'), ('rejected', 'Rejected by Supervisor'), ('needs_assignment_approval', 'Needs Assignment Approval'), ('assigned', 'Assigned to Student'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('closed', 'Closed (Finalized)')], default='new', max_length=30, verbose_name='Status'),
        ),
    ]
