# Generated by Django 5.0.4 on 2025-12-27 14:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Backup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('backup_type', models.CharField(choices=[('database', 'Database'), ('files', 'Files'), ('full', 'Full Backup (Database + Files)')], max_length=20, verbose_name='Backup Type')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20, verbose_name='Status')),
                ('trigger_source', models.CharField(choices=[('manual', 'Manual'), ('scheduled', 'Scheduled'), ('system', 'System')], default='manual', max_length=20, verbose_name='Triggered By')),
                ('database_backup_path', models.CharField(blank=True, max_length=500, null=True, verbose_name='Database Backup Path')),
                ('files_backup_path', models.CharField(blank=True, max_length=500, null=True, verbose_name='Files Backup Path')),
                ('database_size', models.BigIntegerField(default=0, verbose_name='Database Size (bytes)')),
                ('files_size', models.BigIntegerField(default=0, verbose_name='Files Size (bytes)')),
                ('total_size', models.BigIntegerField(default=0, verbose_name='Total Size (bytes)')),
                ('storage_type', models.CharField(choices=[('local', 'Local Storage'), ('s3', 'S3 Storage')], default='local', max_length=20, verbose_name='Storage Type')),
                ('storage_path', models.CharField(blank=True, max_length=500, null=True, verbose_name='Storage Root Path')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description / Notes')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='Error Message')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Started At')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Completed At')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who initiated the backup', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_backups', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
            ],
            options={
                'verbose_name': 'Backup',
                'verbose_name_plural': 'Backups',
                'db_table': 'backups',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='backups_status_c02d44_idx'), models.Index(fields=['backup_type'], name='backups_backup__1988f1_idx'), models.Index(fields=['created_at'], name='backups_created_f8ef12_idx')],
            },
        ),
    ]
