# Generated by Django 5.0.4 on 2026-01-06 15:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='supportticket',
            new_name='support_sup_status_c67c70_idx',
            old_name='support_ticket_status_priority_idx',
        ),
        migrations.RenameIndex(
            model_name='supportticket',
            new_name='support_sup_created_f7fb2d_idx',
            old_name='support_ticket_created_by_idx',
        ),
        migrations.RenameIndex(
            model_name='supportticket',
            new_name='support_sup_assigne_53b075_idx',
            old_name='support_ticket_assigned_to_idx',
        ),
        migrations.AlterField(
            model_name='supportticket',
            name='assigned_to',
            field=models.ForeignKey(blank=True, limit_choices_to={'role__name': 'tech_support'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_support_tickets', to=settings.AUTH_USER_MODEL, verbose_name='Assigned Tech Support'),
        ),
        migrations.AlterField(
            model_name='supportticket',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support_tickets', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
    ]
