# Generated by Django 5.0.4 on 2025-12-10 16:53

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(help_text='Rating score (usually 1-5 or 1-10)', verbose_name='Rating')),
                ('comment', models.TextField(blank=True, help_text='Evaluator comment about the service or performance', null=True, verbose_name='Comment')),
                ('evaluator_type', models.CharField(choices=[('patient', 'Patient'), ('supervisor', 'Supervisor'), ('student', 'Student'), ('university', 'University'), ('admin', 'Admin Dashboard')], help_text='Type of evaluator (Patient, Supervisor, Student, University, Admin Dashboard)', max_length=50, verbose_name='Evaluator Type')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('appointment', models.ForeignKey(blank=True, db_column='appointment_id', help_text='Appointment being evaluated', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evaluations', to='appointments.appointment', verbose_name='Appointment')),
                ('patient', models.ForeignKey(blank=True, db_column='patient_id', help_text='Patient who gave or received the evaluation', limit_choices_to={'role': 'patient'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patient_evaluations', to=settings.AUTH_USER_MODEL, verbose_name='Patient')),
                ('student', models.ForeignKey(blank=True, db_column='student_id', help_text='Student who participated in the service/appointment and was evaluated', limit_choices_to={'role': 'student'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_evaluations', to=settings.AUTH_USER_MODEL, verbose_name='Student')),
            ],
            options={
                'verbose_name': 'Evaluation',
                'verbose_name_plural': 'Evaluations',
                'db_table': 'evaluations',
                'ordering': ['-created_at'],
            },
        ),
    ]
