# Generated by Django 5.0.4 on 2026-01-01 21:02

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointments', '0002_rename_appointment_appoint_8b74ac_idx_idx_appt_date_and_more'),
        ('cases', '0002_alter_caseassignmentrequest_unique_together_and_more'),
        ('universities', '0003_course'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_type', models.CharField(choices=[('case', 'Case'), ('session', 'Session'), ('appointment', 'Appointment')], max_length=20, verbose_name='Evaluation Target Type')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('final', 'Final')], default='draft', max_length=20, verbose_name='Status')),
                ('score', models.PositiveSmallIntegerField(help_text='Score from 0 to 100', verbose_name='Score')),
                ('rubric', models.JSONField(blank=True, default=dict, help_text='Flexible evaluation criteria stored as JSON', verbose_name='Rubric')),
                ('comment', models.TextField(blank=True, verbose_name='Evaluator Comment')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='Submitted At')),
                ('finalized_at', models.DateTimeField(blank=True, null=True, verbose_name='Finalized At')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='evaluations', to='appointments.appointment', verbose_name='Appointment')),
                ('case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='evaluations', to='cases.case', verbose_name='Case')),
                ('evaluator', models.ForeignKey(help_text='Supervisor or university admin who performed the evaluation', limit_choices_to={'role__name__in': ['supervisor', 'university_admin']}, on_delete=django.db.models.deletion.PROTECT, related_name='given_evaluations', to=settings.AUTH_USER_MODEL, verbose_name='Evaluator')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='evaluations', to='cases.casesession', verbose_name='Session')),
                ('student', models.ForeignKey(limit_choices_to={'role__name': 'student'}, on_delete=django.db.models.deletion.PROTECT, related_name='received_evaluations', to=settings.AUTH_USER_MODEL, verbose_name='Student')),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evaluations', to='universities.university', verbose_name='University')),
            ],
            options={
                'verbose_name': 'Evaluation',
                'verbose_name_plural': 'Evaluations',
                'db_table': 'evaluations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='evaluation',
            constraint=models.CheckConstraint(check=models.Q(('score__gte', 0), ('score__lte', 100)), name='evaluation_score_between_0_and_100'),
        ),
        migrations.AddConstraint(
            model_name='evaluation',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('target_type', 'case'), ('case__isnull', False), ('session__isnull', True), ('appointment__isnull', True)), models.Q(('target_type', 'session'), ('case__isnull', True), ('session__isnull', False), ('appointment__isnull', True)), models.Q(('target_type', 'appointment'), ('case__isnull', True), ('session__isnull', True), ('appointment__isnull', False)), _connector='OR'), name='evaluation_exactly_one_target'),
        ),
        migrations.AddConstraint(
            model_name='evaluation',
            constraint=models.UniqueConstraint(condition=models.Q(('case__isnull', False)), fields=('evaluator', 'student', 'case'), name='unique_case_evaluation_per_evaluator'),
        ),
        migrations.AddConstraint(
            model_name='evaluation',
            constraint=models.UniqueConstraint(condition=models.Q(('session__isnull', False)), fields=('evaluator', 'student', 'session'), name='unique_session_evaluation_per_evaluator'),
        ),
        migrations.AddConstraint(
            model_name='evaluation',
            constraint=models.UniqueConstraint(condition=models.Q(('appointment__isnull', False)), fields=('evaluator', 'student', 'appointment'), name='unique_appointment_evaluation_per_evaluator'),
        ),
    ]
