# Generated by Django 5.0.4 on 2025-12-10 16:53

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cases', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIDiagnosis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('symptoms', models.TextField(verbose_name='Symptoms')),
                ('diagnosis', models.TextField(verbose_name='Diagnosis')),
                ('confidence_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=20, verbose_name='Confidence Level')),
                ('recommendations', models.TextField(blank=True, null=True, verbose_name='Recommendations')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_diagnoses', to='cases.case', verbose_name='Case')),
                ('patient', models.ForeignKey(limit_choices_to={'role': 'patient'}, on_delete=django.db.models.deletion.CASCADE, related_name='ai_diagnoses', to=settings.AUTH_USER_MODEL, verbose_name='Patient')),
            ],
            options={
                'verbose_name': 'AI Diagnosis',
                'verbose_name_plural': 'AI Diagnoses',
                'db_table': 'ai_diagnoses',
                'ordering': ['-created_at'],
            },
        ),
    ]
