# Generated by Django 5.0.4 on 2025-12-21 20:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cases', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIDiagnosis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('raw_symptoms', models.TextField(help_text='Original text after speech-to-text or manual input', verbose_name='Raw Symptoms Input')),
                ('normalized_symptoms', models.TextField(blank=True, help_text='Cleaned and normalized Arabic text', null=True, verbose_name='Normalized Symptoms')),
                ('diagnosis_label', models.CharField(help_text='Internal diagnosis identifier (technical)', max_length=255, verbose_name='Diagnosis Label')),
                ('confidence_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=20, verbose_name='Confidence Level')),
                ('severity_level', models.CharField(choices=[('low', 'Low'), ('moderate', 'Moderate'), ('high', 'High')], max_length=20, verbose_name='Severity Level')),
                ('urgency_level', models.CharField(choices=[('non_urgent', 'Non Urgent'), ('urgent', 'Urgent')], max_length=20, verbose_name='Urgency Level')),
                ('ai_metadata', models.JSONField(blank=True, help_text='Technical AI output (rules fired, similarity scores, alternatives)', null=True, verbose_name='AI Metadata')),
                ('patient_explanation', models.TextField(help_text='Safe, non-alarming explanation shown to the patient', verbose_name='Patient Explanation')),
                ('recommendations', models.TextField(blank=True, help_text='General advice and next steps', null=True, verbose_name='Recommendations')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('reviewed', 'Reviewed by Supervisor')], default='pending', max_length=20, verbose_name='Status')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='Reviewed At')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('case', models.ForeignKey(help_text='Clinical case related to this AI analysis', on_delete=django.db.models.deletion.CASCADE, related_name='ai_diagnoses', to='cases.case', verbose_name='Case')),
                ('patient', models.ForeignKey(limit_choices_to={'role__name': 'patient'}, on_delete=django.db.models.deletion.CASCADE, related_name='ai_diagnoses', to=settings.AUTH_USER_MODEL, verbose_name='Patient')),
                ('requested_by', models.ForeignKey(blank=True, help_text='User who initiated the AI analysis', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_ai_diagnoses', to=settings.AUTH_USER_MODEL, verbose_name='Requested By')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_ai_diagnoses', to=settings.AUTH_USER_MODEL, verbose_name='Reviewed By')),
            ],
            options={
                'verbose_name': 'AI Diagnosis',
                'verbose_name_plural': 'AI Diagnoses',
                'db_table': 'ai_diagnoses',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['patient'], name='ai_diagnose_patient_6f588a_idx'), models.Index(fields=['case'], name='ai_diagnose_case_id_189faf_idx'), models.Index(fields=['status'], name='ai_diagnose_status_fdcec6_idx'), models.Index(fields=['created_at'], name='ai_diagnose_created_56eea3_idx')],
            },
        ),
    ]
