# Generated by Django 5.0.4 on 2025-12-26 20:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0001_initial'),
        ('cases', '0002_alter_caseassignmentrequest_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='aidiagnosis',
            name='detected_findings',
            field=models.JSONField(blank=True, help_text='Structured list of findings (JSON)', null=True, verbose_name='Detected Findings'),
        ),
        migrations.AddField(
            model_name='aidiagnosis',
            name='error_message',
            field=models.TextField(blank=True, default='', help_text='Set when engine fails', verbose_name='Error Message'),
        ),
        migrations.AddField(
            model_name='aidiagnosis',
            name='primary_diagnosis',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Primary Diagnosis'),
        ),
        migrations.AddField(
            model_name='aidiagnosis',
            name='report_text',
            field=models.TextField(blank=True, null=True, verbose_name='Detailed Report Text'),
        ),
        migrations.AddField(
            model_name='aidiagnosis',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='aidiagnosis',
            name='ai_metadata',
            field=models.JSONField(blank=True, help_text='Technical output payload from engine (kept for audit/debug)', null=True, verbose_name='AI Metadata'),
        ),
        migrations.AlterField(
            model_name='aidiagnosis',
            name='case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_diagnoses', to='cases.case', verbose_name='Case'),
        ),
        migrations.AlterField(
            model_name='aidiagnosis',
            name='diagnosis_label',
            field=models.CharField(blank=True, default='', help_text='Internal label returned by engine/fusion (technical)', max_length=255, verbose_name='Diagnosis Label'),
        ),
        migrations.AlterField(
            model_name='aidiagnosis',
            name='normalized_symptoms',
            field=models.TextField(blank=True, null=True, verbose_name='Normalized Symptoms'),
        ),
        migrations.AlterField(
            model_name='aidiagnosis',
            name='patient_explanation',
            field=models.TextField(blank=True, default='', verbose_name='Patient Explanation'),
        ),
        migrations.AlterField(
            model_name='aidiagnosis',
            name='raw_symptoms',
            field=models.TextField(verbose_name='Raw Symptoms Input'),
        ),
        migrations.AlterField(
            model_name='aidiagnosis',
            name='recommendations',
            field=models.TextField(blank=True, null=True, verbose_name='Recommendations'),
        ),
        migrations.AlterField(
            model_name='aidiagnosis',
            name='requested_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_ai_diagnoses', to=settings.AUTH_USER_MODEL, verbose_name='Requested By'),
        ),
        migrations.AlterField(
            model_name='aidiagnosis',
            name='severity_level',
            field=models.CharField(choices=[('low', 'Low'), ('moderate', 'Moderate'), ('high', 'High')], default='moderate', max_length=20, verbose_name='Severity Level'),
        ),
        migrations.AlterField(
            model_name='aidiagnosis',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('reviewed', 'Reviewed by Supervisor')], default='pending', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='aidiagnosis',
            name='urgency_level',
            field=models.CharField(choices=[('non_urgent', 'Non Urgent'), ('urgent', 'Urgent')], default='non_urgent', max_length=20, verbose_name='Urgency Level'),
        ),
    ]
