# Generated by Django 5.0.4 on 2026-09-29 01:04

import apps.ai.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0002_aidiagnosis_detected_findings_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIImageUpload',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.FileField(upload_to=apps.ai.models._ai_image_upload_path, verbose_name='Image')),
                ('content_type', models.CharField(max_length=32, verbose_name='Content Type')),
                ('size_bytes', models.PositiveIntegerField(verbose_name='Size (bytes)')),
                ('width', models.PositiveIntegerField(verbose_name='Width')),
                ('height', models.PositiveIntegerField(verbose_name='Height')),
                ('sha256', models.CharField(max_length=64, verbose_name='SHA-256')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('diagnosis', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='images', to='ai.aidiagnosis', verbose_name='Diagnosis')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_image_uploads', to=settings.AUTH_USER_MODEL, verbose_name='Patient')),
            ],
            options={
                'verbose_name': 'AI Image Upload',
                'verbose_name_plural': 'AI Image Uploads',
                'db_table': 'ai_image_uploads',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['patient', 'created_at'], name='ai_image_up_patient_f9251d_idx')],
            },
        ),
    ]
