# Generated by Django 5.0.4 on 2025-12-27 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='audit_logs_user_id_d685f3_idx',
            old_name='audit_logs_user_actio_idx',
        ),
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='audit_logs_univers_90e64b_idx',
            old_name='audit_logs_university_created_idx',
        ),
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='audit_logs_created_262184_idx',
            old_name='audit_logs_created_idx',
        ),
    ]
