# Generated by Django 5.0.4 on 2025-12-10 16:53

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('universities', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('academic', 'Academic Performance'), ('clinical', 'Clinical Performance'), ('attendance', 'Attendance'), ('evaluation', 'Evaluation Summary'), ('progress', 'Progress Report'), ('statistical', 'Statistical Analysis'), ('other', 'Other')], db_column='report_type', max_length=50, verbose_name='Report Type')),
                ('file_url', models.TextField(db_column='file_url', help_text='URL or path to the generated report file', verbose_name='File URL')),
                ('generated_at', models.DateTimeField(auto_now_add=True, db_column='generated_at', verbose_name='Generated At')),
                ('title', models.CharField(blank=True, help_text='Optional title for the report', max_length=200, null=True, verbose_name='Title')),
                ('description', models.TextField(blank=True, help_text='Optional description or notes about the report', null=True, verbose_name='Description')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this report is active and visible', verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('generated_by', models.ForeignKey(blank=True, db_column='generated_by', help_text='User who generated this report', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_reports', to=settings.AUTH_USER_MODEL, verbose_name='Generated By')),
                ('student', models.ForeignKey(db_column='student_id', limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to=settings.AUTH_USER_MODEL, verbose_name='Student')),
                ('university', models.ForeignKey(db_column='university_id', on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='universities.university', verbose_name='University')),
            ],
            options={
                'verbose_name': 'Report',
                'verbose_name_plural': 'Reports',
                'db_table': 'reports',
                'ordering': ['-generated_at'],
                'indexes': [models.Index(fields=['student', 'report_type'], name='reports_student_359caa_idx'), models.Index(fields=['university', 'generated_at'], name='reports_univers_45de7b_idx'), models.Index(fields=['generated_at'], name='reports_generat_a38578_idx')],
            },
        ),
    ]
