# Generated by Django 5.0.4 on 2025-12-30 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='report',
            new_name='reports_student_359caa_idx',
            old_name='reports_student_report_type_idx',
        ),
        migrations.RenameIndex(
            model_name='report',
            new_name='reports_univers_d7623c_idx',
            old_name='reports_university_report_type_idx',
        ),
        migrations.RenameIndex(
            model_name='report',
            new_name='reports_generat_a38578_idx',
            old_name='reports_generated_at_idx',
        ),
        migrations.RenameIndex(
            model_name='report',
            new_name='reports_case_id_26318e_idx',
            old_name='reports_case_id_idx',
        ),
        migrations.RenameIndex(
            model_name='report',
            new_name='reports_session_0cb086_idx',
            old_name='reports_session_id_idx',
        ),
        migrations.AlterField(
            model_name='report',
            name='case_id',
            field=models.UUIDField(blank=True, db_index=True, help_text='Optional case identifier', null=True, verbose_name='Case ID'),
        ),
        migrations.AlterField(
            model_name='report',
            name='session_id',
            field=models.UUIDField(blank=True, db_index=True, help_text='Optional session identifier', null=True, verbose_name='Session ID'),
        ),
    ]
