# Generated by Django 5.0.4 on 2026-01-07 10:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_reports_workflow'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='report',
            new_name='reports_target__f1c53d_idx',
            old_name='reports_target_idx',
        ),
        migrations.AlterField(
            model_name='report',
            name='generated_by',
            field=models.ForeignKey(blank=True, help_text='User who generated this report', limit_choices_to={'role__name__in': ['supervisor', 'university_admin']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_reports', to=settings.AUTH_USER_MODEL, verbose_name='Generated By'),
        ),
        migrations.AlterField(
            model_name='report',
            name='report_type',
            field=models.CharField(choices=[('clinical_case', 'Clinical Case Report'), ('supervisor_case_evaluation', 'Supervisor Case Evaluation'), ('student_performance', 'Student Performance'), ('course_performance', 'Course Performance'), ('university_students', 'University Student Summary'), ('university_supervisors', 'University Supervisor Summary'), ('university_archive', 'University Archive Report'), ('other', 'Other')], db_index=True, max_length=50, verbose_name='Report Type'),
        ),
    ]
