# Generated by Django 5.0.4 on 2025-12-21 20:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cases', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_date', models.DateTimeField(help_text='Scheduled date and time for the appointment.', verbose_name='Appointment Date')),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('confirmed', 'Confirmed'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('no_show', 'No Show')], default='scheduled', max_length=20, verbose_name='Status')),
                ('is_follow_up', models.BooleanField(default=False, help_text='Indicates if this appointment is a follow-up.', verbose_name='Follow-up Appointment')),
                ('notes', models.TextField(blank=True, help_text='Optional notes by student or supervisor.', null=True, verbose_name='Internal Notes')),
                ('is_archived', models.BooleanField(default=False, help_text='Soft-hide old appointments without deletion.', verbose_name='Archived')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('case', models.ForeignKey(help_text='Dental case this appointment belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='cases.case', verbose_name='Related Case')),
                ('created_by', models.ForeignKey(help_text='User who created the appointment.', limit_choices_to={'role__in': ['student', 'supervisor']}, on_delete=django.db.models.deletion.PROTECT, related_name='created_appointments', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('patient', models.ForeignKey(limit_choices_to={'role': 'patient'}, on_delete=django.db.models.deletion.CASCADE, related_name='patient_appointments', to=settings.AUTH_USER_MODEL, verbose_name='Patient')),
                ('student', models.ForeignKey(help_text='Student responsible for this appointment.', limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='student_appointments', to=settings.AUTH_USER_MODEL, verbose_name='Student')),
                ('supervisor', models.ForeignKey(blank=True, limit_choices_to={'role': 'supervisor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervised_appointments', to=settings.AUTH_USER_MODEL, verbose_name='Supervisor')),
            ],
            options={
                'verbose_name': 'Appointment',
                'verbose_name_plural': 'Appointments',
                'db_table': 'appointments',
                'ordering': ['-appointment_date'],
                'indexes': [models.Index(fields=['appointment_date'], name='appointment_appoint_8b74ac_idx'), models.Index(fields=['status'], name='appointment_status_9fecd6_idx'), models.Index(fields=['student'], name='appointment_student_ba3dac_idx'), models.Index(fields=['patient'], name='appointment_patient_75a4eb_idx')],
            },
        ),
    ]
