# Generated by Django 5.0.4 on 2025-12-26 20:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
        ('cases', '0002_alter_caseassignmentrequest_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='appointment',
            new_name='idx_appt_date',
            old_name='appointment_appoint_8b74ac_idx',
        ),
        migrations.RenameIndex(
            model_name='appointment',
            new_name='idx_appt_status',
            old_name='appointment_status_9fecd6_idx',
        ),
        migrations.RenameIndex(
            model_name='appointment',
            new_name='idx_appt_student',
            old_name='appointment_student_ba3dac_idx',
        ),
        migrations.RenameIndex(
            model_name='appointment',
            new_name='idx_appt_patient',
            old_name='appointment_patient_75a4eb_idx',
        ),
        migrations.AlterField(
            model_name='appointment',
            name='created_by',
            field=models.ForeignKey(help_text='User who created the appointment.', limit_choices_to={'role__name__in': ['student', 'supervisor']}, on_delete=django.db.models.deletion.PROTECT, related_name='created_appointments', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='patient',
            field=models.ForeignKey(limit_choices_to={'role__name': 'patient'}, on_delete=django.db.models.deletion.CASCADE, related_name='patient_appointments', to=settings.AUTH_USER_MODEL, verbose_name='Patient'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='student',
            field=models.ForeignKey(help_text='Student responsible for this appointment.', limit_choices_to={'role__name': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='student_appointments', to=settings.AUTH_USER_MODEL, verbose_name='Student'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='supervisor',
            field=models.ForeignKey(blank=True, limit_choices_to={'role__name': 'supervisor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervised_appointments', to=settings.AUTH_USER_MODEL, verbose_name='Supervisor'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['case'], name='idx_appt_case'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['is_archived'], name='idx_appt_archived'),
        ),
    ]
