# Generated by Django 5.0.4 on 2026-01-08 17:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_rename_appointment_appoint_8b74ac_idx_idx_appt_date_and_more'),
    ]

    operations = [
        # Align DB schema with current model: rename old column and add missing fields
        migrations.RenameField(
            model_name='appointment',
            old_name='appointment_date',
            new_name='scheduled_at',
        ),
        migrations.AddField(
            model_name='appointment',
            name='duration_minutes',
            field=models.PositiveSmallIntegerField(default=30, help_text='Expected duration of the appointment.', verbose_name='Duration (minutes)'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='location',
            field=models.CharField(blank=True, help_text='Physical location if in-person.', max_length=255, null=True, verbose_name='Location'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='telehealth_link',
            field=models.URLField(blank=True, help_text='Virtual meeting link if remote.', max_length=500, null=True, verbose_name='Telehealth Link'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='scheduled_at',
            field=models.DateTimeField(help_text='Scheduled date and time for the appointment.', verbose_name='Scheduled At'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('rescheduled', 'Rescheduled'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('no_show', 'No Show')], default='scheduled', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='student',
            field=models.ForeignKey(blank=True, help_text='Student responsible for this appointment (nullable before assignment).', limit_choices_to={'role__name': 'student'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_appointments', to='accounts.user', verbose_name='Student'),
        ),
    ]
