# Generated by Django 5.0.4 on 2026-01-08 17:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_scheduled_at_field_update'),
        ('cases', '0005_alter_case_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'ordering': ['-scheduled_at'], 'verbose_name': 'Appointment', 'verbose_name_plural': 'Appointments'},
        ),
        migrations.RemoveIndex(
            model_name='appointment',
            name='idx_appt_date',
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['scheduled_at'], name='idx_appt_date'),
        ),
    ]
