# Generated by Django 5.0.4 on 2025-12-10 16:53

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('universities', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('description', models.TextField(verbose_name='Description')),
                ('content_type', models.CharField(choices=[('article', 'Article'), ('video', 'Video'), ('document', 'Document'), ('image', 'Image'), ('link', 'Link')], max_length=20, verbose_name='Content Type')),
                ('category', models.CharField(choices=[('medical', 'Medical'), ('educational', 'Educational'), ('research', 'Research'), ('news', 'News'), ('general', 'General')], max_length=20, verbose_name='Category')),
                ('file', models.FileField(blank=True, null=True, upload_to='community_files/', verbose_name='File')),
                ('url', models.URLField(blank=True, null=True, verbose_name='URL')),
                ('tags', models.CharField(blank=True, max_length=500, null=True, verbose_name='Tags')),
                ('is_public', models.BooleanField(default=True, verbose_name='Is Public')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Is Featured')),
                ('status', models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='approved', help_text='For students: requires supervisor approval. Others: auto-approved.', max_length=20, verbose_name='Status')),
                ('rejection_reason', models.TextField(blank=True, help_text='Reason for rejection if status is rejected', null=True, verbose_name='Rejection Reason')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='Approved At')),
                ('view_count', models.PositiveIntegerField(default=0, verbose_name='View Count')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('approved_by', models.ForeignKey(blank=True, help_text='Supervisor or admin who approved/rejected this content', limit_choices_to={'role__in': ['supervisor', 'university_admin', 'tech_support']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_content', to=settings.AUTH_USER_MODEL, verbose_name='Approved By')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authored_content', to=settings.AUTH_USER_MODEL, verbose_name='Author')),
                ('university', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='content', to='universities.university', verbose_name='University')),
            ],
            options={
                'verbose_name': 'Content',
                'verbose_name_plural': 'Content',
                'db_table': 'community_content',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContentComment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.TextField(verbose_name='Text')),
                ('is_approved', models.BooleanField(default=True, verbose_name='Is Approved')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='community.content', verbose_name='Content')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='community.contentcomment', verbose_name='Parent Comment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Content Comment',
                'verbose_name_plural': 'Content Comments',
                'db_table': 'content_comments',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContentLike',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='community.content', verbose_name='Content')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liked_content', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Content Like',
                'verbose_name_plural': 'Content Likes',
                'db_table': 'content_likes',
            },
        ),
        migrations.AddIndex(
            model_name='content',
            index=models.Index(fields=['status', 'author'], name='community_c_status_63baf7_idx'),
        ),
        migrations.AddIndex(
            model_name='content',
            index=models.Index(fields=['status', 'created_at'], name='community_c_status_1ce87b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='contentlike',
            unique_together={('content', 'user')},
        ),
    ]
