# Generated by Django 5.0.4 on 2026-01-06 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='contentlike',
            name='community_like_content_user_idx',
        ),
        migrations.RenameIndex(
            model_name='content',
            new_name='community_c_status_20bb43_idx',
            old_name='community_content_status_idx',
        ),
        migrations.RenameIndex(
            model_name='content',
            new_name='community_c_author__6c48a8_idx',
            old_name='community_content_author_idx',
        ),
        migrations.RenameIndex(
            model_name='content',
            new_name='community_c_univers_8e6515_idx',
            old_name='community_content_university_idx',
        ),
        migrations.AlterField(
            model_name='contentcomment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
