# Generated by Django 5.0.4 on 2026-01-07 00:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0003_community_approval_log_and_soft_delete'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='communityapprovallog',
            new_name='community_a_univers_5ddaa9_idx',
            old_name='community_approval_decision_idx',
        ),
        migrations.RenameIndex(
            model_name='communityapprovallog',
            new_name='community_a_post_id_6f8bc4_idx',
            old_name='community_approval_post_created_idx',
        ),
        migrations.RenameIndex(
            model_name='content',
            new_name='community_c_univers_af5fb4_idx',
            old_name='community_university_status_idx',
        ),
        migrations.AlterField(
            model_name='content',
            name='approved_by',
            field=models.ForeignKey(blank=True, limit_choices_to={'role__name__in': ['supervisor']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_content', to=settings.AUTH_USER_MODEL, verbose_name='Approved / Rejected By'),
        ),
        migrations.AlterField(
            model_name='content',
            name='content_type',
            field=models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('case', 'Clinical Case'), ('video', 'Video')], max_length=20, verbose_name='Content Type'),
        ),
        migrations.AlterField(
            model_name='content',
            name='description',
            field=models.TextField(verbose_name='Content'),
        ),
        migrations.AlterModelTable(
            name='communityapprovallog',
            table='community_approval_logs',
        ),
    ]
