# Generated by Django 5.0.4 on 2026-01-07 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0004_content_image_variants_and_type_update'),
        ('community', '0004_rename_community_approval_decision_idx_community_a_univers_5ddaa9_idx_and_more'),
    ]

    operations = [
    ]
