# Generated by Django 5.0.4 on 2025-12-31 11:33

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointments', '0002_rename_appointment_appoint_8b74ac_idx_idx_appt_date_and_more'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notification_type', models.CharField(choices=[('appointment_reminder', 'Appointment Reminder'), ('appointment_update_request', 'Appointment Update Request'), ('appointment_cancel_request', 'Appointment Cancel Request'), ('appointment_status_update', 'Appointment Status Update'), ('report_submitted', 'Report Submitted'), ('report_reviewed', 'Report Reviewed'), ('evaluation_submitted', 'Evaluation Submitted'), ('ai_analysis_ready', 'AI Analysis Ready'), ('community_content_pending', 'Content Pending Approval'), ('community_content_approved', 'Content Approved'), ('community_content_rejected', 'Content Rejected'), ('case_created', 'Case Created'), ('case_assigned', 'Case Assigned'), ('case_status_changed', 'Case Status Changed'), ('session_created', 'Session Created'), ('session_needs_review', 'Session Needs Review'), ('session_reviewed', 'Session Reviewed'), ('new_message', 'New Message'), ('system_alert', 'System Alert'), ('backup_status', 'Backup Status'), ('security_event', 'Security Event')], max_length=50, verbose_name='Notification Type')),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('critical', 'Critical')], default='normal', max_length=20, verbose_name='Priority')),
                ('target_object_id', models.UUIDField(blank=True, null=True, verbose_name='Target Object ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('message', models.TextField(verbose_name='Message')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('info', 'Informational')], default='info', max_length=20, verbose_name='Status')),
                ('response_message', models.TextField(blank=True, null=True, verbose_name='Response Message')),
                ('proposed_changes', models.JSONField(blank=True, help_text='Used for update requests or approvals.', null=True, verbose_name='Proposed Changes')),
                ('payload', models.JSONField(blank=True, help_text='Optional structured payload for frontend.', null=True, verbose_name='Payload')),
                ('is_read', models.BooleanField(default=False, verbose_name='Is Read')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='Read At')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='appointments.appointment', verbose_name='Appointment')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_notifications', to=settings.AUTH_USER_MODEL, verbose_name='Recipient')),
                ('sender', models.ForeignKey(blank=True, help_text='User who triggered the notification (can be null for system events).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_notifications', to=settings.AUTH_USER_MODEL, verbose_name='Sender')),
                ('target_content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype', verbose_name='Target Content Type')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'db_table': 'notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient'], name='notificatio_recipie_1dd18d_idx'), models.Index(fields=['notification_type'], name='notificatio_notific_19df93_idx'), models.Index(fields=['is_read'], name='notificatio_is_read_3f8c44_idx'), models.Index(fields=['created_at'], name='notificatio_created_e4c995_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='notification',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('target_content_type__isnull', True), ('target_object_id__isnull', True)), models.Q(('target_content_type__isnull', False), ('target_object_id__isnull', False)), _connector='OR'), name='notifications_target_type_id_consistency'),
        ),
    ]
